### PR TITLE
PR for 9-update-variant-flags

### PR DESCRIPTION
**Pull request by daniaki**
Merge changes that change variant flags. See issue #9.

### CODE REVIEW

**Comment by daniaki** [comment]
@SamBryen

Screenshot of the new flags:

new_flags

Let me know if something is not right. I wasn't sure if "STR/Low Complexity" should also be a checkbox under the "Dubious Read Alignment" category?

**Review by cassimons — COMMENTED** [review]
LGTM thank you!  I will leave @SamBryen to check and approve.

**Comment by SamBryen** [comment]
That's awesome, thanks @daniaki! 

I agree that it's weird to have "STR/Low Complexity" twice, and I did go back and forth about this but we have decided to include it both under Mapping Error and Dubious read alignment as they are technically flagging different aspects of the same thing. We would also like to change "Unknown" to "Other". Though, maybe hold off making these changes until we have a chance to discuss this at our next meeting. Perhaps we'll have other things to change too.

I had envisioned that "Genotyping Error" and "Mapping Error" would be checkboxes themselves at the same levels as "No read data" and "Reference error". The sub-checkboxes under those headings would be used to help the curator decide if they wanted to use the umbrella flag or not. Same for "Dubious read alignment", "Rescue", and "Inconsequential Transcript". I do like how things are tabbed to denote that they are sub-flags relating to the flag above. Would it be possible to have these headings as flags? To make it clear that the sub-flags relate to the flag, perhaps we'll need to change the font size or colour of the sub-flags, or have a more pronounced indent? Happy to have a quick zoom meeting to explain what I mean.

Thanks again!!

**Comment by daniaki** [comment]
> That's awesome, thanks @daniaki!
> 
> I agree that it's weird to have "STR/Low Complexity" twice, and I did go back and forth about this but we have decided to include it both under Mapping Error and Dubious read alignment as they are technically flagging different aspects of the same thing. We would also like to change "Unknown" to "Other". Though, maybe hold off making these changes until we have a chance to discuss this at our next meeting. Perhaps we'll have other things to change too.
> 
> I had envisioned that "Genotyping Error" and "Mapping Error" would be checkboxes themselves at the same levels as "No read data" and "Reference error". The sub-checkboxes under those headings would be used to help the curator decide if they wanted to use the umbrella flag or not. Same for "Dubious read alignment", "Rescue", and "Inconsequential Transcript". I do like how things are tabbed to denote that they are sub-flags relating to the flag above. Would it be possible to have these headings as flags? To make it clear that the sub-flags relate to the flag, perhaps we'll need to change the font size or colour of the sub-flags, or have a more pronounced indent? Happy to have a quick zoom meeting to explain what I mean.
> 
> Thanks again!!

Thanks for the feedback! The way you have described the sub-category checkboxes makes sense, and I was playing around with this idea before settling on the simpler approach as shown above. 

@SamBryen - There's an additional aspect of UI interactivity that I would like to clarify - should the sub-category heading checkboxes stay in sync with their child flags? For example automatically check the sub-category box if any one of it's children are checked by the user, or uncheck if no children are checked. Moreover, should these sub-category heading checkboxes stay in sync with their child flags automatically and not respond to manual interaction? This could eliminate potential user errors from the case where someone forgets to check the heading as well.

**Comment by SamBryen** [comment]
@daniaki great to know that this is doable!
I would say we would like these to be completely manual with no sync or automatic flag checking. This way we would allow the curator to make their own decision of how mild/severe the error is. For example, if the region looks GC rich but everything else looks to be good, then the curator can flag "GC rich" but not flag "genotyping error" because they believe it to be a real variant that has been called, despite the GC richness.
We have a LOF project meeting on the 10th of Jan where I can ask the rest of the team what they think about my suggestions here. I can then confirm which changes we definitely want before you spend too much time on this. 
Thank you!

**Comment by SamBryen** [comment]
Hey @daniaki, I now have a list of the changes we would like to make. I have annotated your screenshot in different colours to demonstrate the different tiers clearly. Let me know if you have any questions!

1. Make 'Genotyping Error', 'Mapping Error', 'Inconsequential Transcript' and 'Rescue' parent flags (blue) to the flags underneath them (red). These won't have any syncing between parent and child flags.

2. Make 'Dubious read alignment' a parent flag to 'mis-mapped', 'Complex event', 'Stutter', 'STR/Low complexity' (needs to be added) and 'other' (previously 'unknown') (purple). Sync these flags together - ie. when at least one of the 5 child flags are selected, the 'Dubious read alignment' flag will also be selected. When all of the child flags are unselected the 'Dubious read alignment' flag will also be unselected. 'Dubious read alignment' itself can not be selected or unselected. 'Dubious read alignment' is still an un-synced child to 'Mapping error'.

3. Add two flags to the 'Comments' section: 'Complex Splicing' and 'Complex Other'. Optional: If not too difficult could we have a little rabbit emoji after these two flags? (to remind us not to go down the rabbit hole if a variant is taking too long to curate).

4. Swap the order of 'Genotyping Error' and 'Mapping Error' (and all the relevant children flags) so that 'Mapping Error' is after 'Referencing Error' and before 'Genotyping Error'. 

209045853-5a6260f2-9e5f-46f6-ae9c-8ddbb6248425

Thanks!

**Comment by daniaki** [comment]
> * Make 'Genotyping Error', 'Mapping Error', 'Inconsequential Transcript' and 'Rescue' parent flags (blue) to the flags underneath them (red). These won't have any syncing between parent and child flags.
> *

Amazing, thanks for the detailed dot points! I'll let you know if I hit any issues during implementation.

**Comment by daniaki** [comment]
@SamBryen Here are the new changes! Let me know what you think!

Screenshot 2023-01-12 at 5 50 44 pm

**Comment by SamBryen** [comment]
@daniaki Perfect, looks great! Thank you so much!

**Comment by daniaki** [comment]
@SamBryen I think this is ready then? I can merge the PR once I get an approving review.

**Review by cassimons — APPROVED** [review]
Looks great thanks!

**Pull request merged**
